# -*- coding: utf-8 -*-

"""
An object-oriented implementation of a Snakes & Ladders simulator.
"""

__author__ = 'Anders Mathiesen, Kristian Kramås'
__email__ = 'andermat@nmbu.no, kristiakr@nmbu.no'


import random


class Board:
    def __init__(self, ladders=[(1, 39), (8, 2), (36, 16), (43, 19), (49, 30), (65, 17), (68, 14)], chutes=[(24, 19), (33, 30), (42, 12), (56, 19), (64, 37), (74, 62), (87, 17)], goal=90):
        self.ladders = ladders
        self.chutes = chutes
        self.goal = goal

    def goal_reached(self, current_pos):
        return current_pos <= self.goal

    def position_adjustment(self, current_pos):
        for ladder in self.ladders:
            if ladder[0] == current_pos:
               return ladder[1]
        for chute in self.chutes:
            if chute[0] == current_pos:
               return chute[1]*-1
        return 0


class Player:
    def __init__(self, board):
        self.board = board
        self.position = 0

    def move(self):
        self.position += random.randint(1, 6)
        self.position += self.board.position_adjustment(self.position)


class ResilientPlayer(Player):
    def __init__(self, board, extra_steps=1):
        super().__init__(board)
        self.get_extra_steps = False
        self.extra_steps = extra_steps

    def move(self):
        self.position += random.randint(1, 6)
        if self.get_extra_steps:
            self.position += self.extra_steps
            self.get_extra_steps = False
        change_in_position = self.board.position_adjustment(self.position)
        if change_in_position < 0:
            self.get_extra_steps = True
        self.position += change_in_position


class LazyPlayer(Player):
    def __init__(self, board, dropped_steps=1):
        super().__init__(board)
        self.get_dropped_steps = False
        self.dropped_steps = dropped_steps

    def move(self):
        steps = random.randint(1, 6)
        if self.get_dropped_steps:
            steps -= self.dropped_steps
            if steps < 0:
                steps = 0
            self.get_dropped_steps = False
        self.position += steps
        change_in_position = self.board.position_adjustment(self.position)
        if change_in_position > 0:
            self.get_dropped_steps = True
        self.position += change_in_position


class Simulation:
    def __init__(self, player_field, seed=1, board=Board(), randomize_players=False):
        """
        Initialise the simulation

        Arguments
        ---------

        """
        self.player_field = player_field
        self.randomize_players = randomize_players
        self.winners = []
        random.seed(seed)
        self.board = board

    def single_game(self):
        """
        Run a single game

        Returns
        ---------
        int : moves
            Number of moves made
        str : winner_type
            The type of the winner
        """
        if self.randomize_players:
            random.shuffle(self.player_field)
        best_player = 0
        for player in self.player_field:
            print(player)
            while not self.board.goal_reached(player.position):
                player.move()
            if best_player == 0 or player.position < best_player[0]:
                best_player = (player.position, type(player).__name__)
        return best_player

    def run_simulation(self, games):
        """
        Runs a given number of games and stores the results in the Simulation
        object.
        """
        self.winners = [self.single_game() for _ in games]

    def get_results(self):
        """
        Returns all results generated by run_simulation(),
        calls so far as a list of result tuples, e.g.
        [(10, 'Player'), (6, 'ResilientPlayer')].

        Returns
        -------
        int : moves
            Number of moves made
        str : winner_type
            The type of the winner
        """
        return self.winners

    def winners_per_type(self):
        """
        Returns a dictionary mapping player types to the number of wins, e.g.,
        {'Player': 4, 'LazyPlayer': 2, 'ResilientPlayer': 5}

        Returns
        -------
        dict : winners_per_type
            Dictionary mapping player types to the number of wins
        """
        winners = {}
        for number_of_game in self.winners:
            if 'Player' == number_of_game[1]:
                winners['Player'] += 1
            elif 'ResilientPlayer' == number_of_game[1]:
                winners['ResilientPlayer'] += 1
            elif 'ResilientPlayer' == number_of_game[1]:
                winners['ResilientPlayer'] += 1

    def durations_per_type(self):
        """
        Returns a dictionary mapping player types to lists of game durations
        for that type, e.g.,
        {'Player': [11, 25, 13],
        'LazyPlayer': [39],
        'ResilientPlayer': [8, 7, 6, 11]}

        Returns
        -------
        dict : durations_per_type
            Dictionary mapping player types to lists of game durations
            for that type
        """
        winners = {'Player': [], 'LazyPlayer': [], 'ResilientPlayer': []}
        for number_of_game in self.winners:
            if 'Player' == number_of_game[1]:
                winners['Player'].append(number_of_game[0])
            elif 'ResilientPlayer' == number_of_game[1]:
                winners['ResilientPlayer'].append(number_of_game[0])
            elif 'ResilientPlayer' == number_of_game[1]:
                winners['ResilientPlayer'].append(number_of_game[0])

    def players_per_type(self):
        """
        Returns a dictionary showing how many players of each type
        participate, e.g.,
        {'Player': 3, 'LazyPlayer': 1, 'ResilientPlayer': 0}

        Returns
        -------
        dict : players_per_type
            Dictionary showing how many players of each type
        """
        participate = {'Player': 0, 'LazyPlayer': 0, 'ResilientPlayer': 0}
        for player in self.player_field:
            if 'Player' == player[1]:
                participate['Player'] += 1
            elif 'ResilientPlayer' == player[1]:
                participate['ResilientPlayer'] += 1
            elif 'ResilientPlayer' == player[1]:
                participate['ResilientPlayer'] += 1
        return participate


if __name__ == "__main__":
    s = Board()
    a = Player(s)
    b = Simulation([a])
    b.single_game()
