# -*- coding: utf-8 -*-

"""
An object-oriented implementation of a Snakes & Ladders simulator.
"""

__author__ = 'Anders Mathiesen, Kristian Kramås'
__email__ = 'andermat@nmbu.no, kristiakr@nmbu.no'


class Board:
    def __init__(self, ladders=[(1, 39), (8, 2), (36, 16), (43, 19), (49, 30), (65, 17), (68, 14)], chutes=[(24, 19), (33, 30), (42, 12), (56, 19), (64, 37), (74, 62), (87, 17)], goal=90):
        self.ladders = ladders
        self.chutes = chutes
        self.goal = goal

    def goal_reached(self, current_pos):
        return current_pos <= self.goal

    def position_adjustment(self, current_pos):
        for ladder in self.ladders:
            if ladder[0] == current_pos:
               return ladder[1]
        for chute in self.chutes:
            if chute[0] == current_pos:
               return chute[1]*-1
        return 0

test = Board()
print(test.position_adjustment(24))


class Player(board):
    def __init__(self, board):
        self.board = board;
        self.position;
        pass

    def move(self):
        pass


class ResilientPlayer(Player):
    def __init__(self):
        super().__init__()


class LazyPlayer(Player):
    def __init__(self):
        super().__init__()


class Simulation(players, randomize_players):
    def __init__(self):
        """
        Initialise the simulation

        Arguments
        ---------

        """
        pass

    def single_game(self):
        """
        Run a single game

        Returns
        ---------
        int : moves
            Number of moves made
        string : winner_type
            The type of the winner
        """
        pass

    def run_simulation(self, games):
        """
        Runs a given number of games and stores the results in the Simulation
        object.
        ---------
        int : moves
            Number of moves made
        string : winner_type
            The type of the winner
        pass
        """

    def get_results(self):
        """
        Returns all results generated by run_simulation(),
        calls so far as a list of result tuples, e.g.
        [(10, 'Player'), (6, 'ResilientPlayer')].
        ---------
        int : moves
            Number of moves made
        string : winner_type
            The type of the winner
        """
        pass

    def winners_per_type(self):
        pass

    def durations_per_type(self):
        pass

    def players_per_type(self):
        pass


if __name__ == "__main__":
    pass
